# SMT-COMP 2025 UnsatCore. Formal scores require the validation phase.
[meta]
name = "cvc5-unsat-core"
track = "UnsatCore"
jobs = 1
cores = 4
memory_mib = 30720
wall_limit_s = 1200

[default]
args = ["--quiet", "--fp-exp", "--use-portfolio"]

[division.QF_Datatypes]
args = []
[division.QF_Equality]
args = []
[division.QF_Equality_LinearArith]
args = []
[division.QF_Equality_NonLinearArith]
args = []
[division.QF_Equality_Bitvec]
args = []
[division.QF_LinearIntArith]
args = []
[division.QF_LinearRealArith]
args = []
[division.QF_Bitvec]
args = []
[division.QF_FPArith]
args = []
[division.QF_NonLinearIntArith]
args = []
[division.QF_NonLinearRealArith]
args = []
[division.QF_Strings]
args = []
[division.Equality]
args = []
[division.Equality_LinearArith]
args = []
[division.Equality_MachineArith]
args = []
[division.Equality_NonLinearArith]
args = []
[division.Arith]
args = []
[division.Bitvec]
args = []
[division.FPArith]
args = []
