# Independent tuning candidate for Parallel/par.
# Rules: https://smt-comp.github.io/2025/rules.pdf
# Official scoring: https://github.com/SMT-COMP/smt-comp.github.io/blob/smtcomp25/smtcomp/scoring.py
[meta]
name = "cvc5-parallel-par"
track = "Parallel"
performance = "par"
jobs = 1
cores = 128
memory_mib = 1024000
wall_limit_s = 1200

[default]
args = ["--fp-exp", "--use-portfolio"]

[division.Arith]
args = []
[division.Bitvec]
args = []
[division.Equality]
args = []
[division.Equality_LinearArith]
args = []
[division.Equality_MachineArith]
args = []
[division.Equality_NonLinearArith]
args = []
[division.FPArith]
args = []
[division.QF_Bitvec]
args = []
[division.QF_Datatypes]
args = []
[division.QF_Equality]
args = []
[division.QF_Equality_Bitvec]
args = []
[division.QF_Equality_LinearArith]
args = []
[division.QF_Equality_NonLinearArith]
args = []
[division.QF_FPArith]
args = []
[division.QF_LinearIntArith]
args = []
[division.QF_LinearRealArith]
args = []
[division.QF_NonLinearIntArith]
args = []
[division.QF_NonLinearRealArith]
args = []
[division.QF_Strings]
args = []
