project: cvc5-config-challenge
profile: default
region: us-east-1
solver_type: smt

solvers:
  - name: cvc5-submission
    author: challenge entrant
    docker_dir: $CVC5_CLOUD_ROOT
    dockerfile: aws-build/Dockerfile
    is_distributed: true
    num_worker_nodes_per_leader: 99
    ec2_instance_type: m6i.4xlarge
    disk_size: 32
